# Generated by Django 5.1 on 2024-08-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="Rating",
            new_name="rating",
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="Restaurant",
            new_name="restaurant",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                choices=[
                    ("IN", "Indian"),
                    ("CH", "Chinese"),
                    ("IT", "Italy"),
                    ("GR", "Greek"),
                    ("MX", "Mexican"),
                    ("FF", "FASTFOOD"),
                    ("OT", "Other"),
                ],
                default="",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income", models.DecimalField(decimal_places=2, max_digits=8)),
                ("datetime", models.DateTimeField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
    ]
